format = """
$username\
[](fg:#512663 bg:#0B7078)\
$directory\
[](fg:#0B7078 bg:#1A596E)\
$python\
[](fg:#1A596E bg:#2B4063)\
[ ](fg:#2B4063)\
$status\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "bg:#512663"
style_root = "bg:#512663"
format = '[✨]($style)'

[directory]
style = "bg:#0B7078"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"~/Documents" = ""
"~/Downloads" = "\uf01a"
"~/Desktop" = "\ufb9b"
"~/workspace" = "\ue796"

# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[python]
format = "[ ${symbol} ]($style)"
style = "bg:#1A596E"
symbol = "\ue235"

[status]
disabled = false
format = "[$symbol]($style) "
style = "fg:#FF3333"
symbol = "\uf06a"
